FROM ubuntu:16.04
MAINTAINER Gigantum <hello@gigantum.io>

# Install system level dependencies
RUN apt-get -y update; apt-get install -y software-properties-common; add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get -y upgrade;
RUN apt-get -y update; apt-get -y install build-essential python3.6-dev libleveldb-dev libleveldb1v5 git nginx supervisor curl gosu redis-server vim

# Install pip with PPA 3.6 installation
RUN curl https://bootstrap.pypa.io/get-pip.py | python3.6

# Setup Global git config
RUN git config --global user.email "noreply@gigantum.io"; git config --global user.name "Gigantum AutoCommit"

# Copy LabManager Package
COPY submodules/labmanager-common /opt/labmanager-common
COPY submodules/labmanager-service-labbook /opt/labmanager-service-labbook

# Install lmcommon
RUN cd /opt/labmanager-common/; pip3.6 install -r /opt/labmanager-common/requirements.txt; python3.6 setup.py install

# Setup lmcommon config file - should be written by automation before copy
COPY labmanager_resources/labmanager-config.yaml /etc/gigantum/labmanager.yaml

# Setup logging config file
COPY submodules/labmanager-common/lmcommon/logging/logging.json.default /etc/gigantum/logging.json

# Install API deps
RUN pip3.6 install -r /opt/labmanager-service-labbook/requirements.txt; pip3.6 install uwsgi
RUN mkdir -p /mnt/gigantum

# Copy frontend
COPY submodules/labmanager-ui/build/ /var/www/

# Setup NGINX/uWSGI
COPY labmanager_resources/nginx_ui.conf /etc/nginx/sites-enabled/
COPY labmanager_resources/nginx_api.conf /etc/nginx/sites-enabled/
RUN rm /etc/nginx/sites-enabled/default

# Setup Redis
RUN mkdir /opt/redis
COPY labmanager_resources/redis.conf /opt/redis/redis.conf

# Setup Supervisord to launch both uwsgi and nginx
RUN mkdir -p /opt/log/supervisor; mkdir -p /opt/log/nginx; mkdir -p /opt/run; mkdir -p /opt/nginx; nginx; nginx -s reload; nginx -s quit
COPY labmanager_resources/supervisord_base.conf /etc/supervisor/supervisord.conf
COPY labmanager_resources/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Copy SSH keys for GitLab AWS instance...
RUN mkdir -p /root/.ssh
COPY developer_resources/id_rsa /root/.ssh
COPY developer_resources/id_rsa.pub /root/.ssh
RUN echo "StrictHostKeyChecking no" > /root/.ssh/config
RUN echo "UserKnownHostsFile /dev/null" >> /root/.ssh/config
RUN chmod 400 /root/.ssh/config
RUN chmod 400 /root/.ssh/id_rsa
RUN chmod 0644 /root/.ssh/id_rsa.pub
RUN ssh -T git@ec2-107-22-88-175.compute-1.amazonaws.com -p 9922


COPY labmanager_resources/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod u+x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Expose Ports
EXPOSE 10000

# Typically start by firing up uwsgi+nginx, but use CMD so it's easy to override
CMD ["/usr/bin/supervisord", "--nodaemon"]
