FROM ubuntu:16.04
MAINTAINER Gigantum <hello@gigantum.io>

# Install system level dependencies
RUN apt-get -y update; apt-get -y install git curl gosu

# Install node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && apt-get -y install nodejs

# Install babel-node
RUN npm install -g babel-cli@6.26.0 jest@21.2.1 relay-compiler@1.5.0 webpack@3.3.0 jsdom-global@3.0.2 jsdom@>=10.0.0

# Install Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
apt-get update && apt-get install yarn

# Make build location dir
RUN mkdir /opt/build_dir

# Set the react port to match nginx
ENV PORT "10001"

# Copy in build script
COPY frontend_resources/build_script.sh /opt/
RUN chmod u+x /opt/build_script.sh

# Setup entrypoint to configure permissions properly
COPY frontend_resources/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod u+x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Run build script on container start
CMD ["/bin/bash", "/opt/build_script.sh"]