FROM ubuntu:16.04
MAINTAINER Gigantum <hello@gigantum.io>

# Install system level dependencies
RUN apt-get -y update; apt-get -y upgrade
RUN apt-get -y install build-essential git curl libtool m4 autotools-dev autoconf automake python-dev gosu

# Install node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get -y install nodejs

# Install Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get install yarn

# Build Watchman
RUN apt-get -y install gtk-doc-tools libtool m4 autotools-dev autoconf automake libssl-dev libcrypto++-dev
RUN git clone https://github.com/facebook/watchman.git; cd watchman; git checkout v4.8.0; ./autogen.sh; ./configure; make; make install

# Make build location dir
RUN mkdir /opt/build_dir

# Set the react port to match nginx
ENV PORT "10001"

# Copy in build script
COPY frontend_resources/build_script.sh /opt/
RUN chmod u+x /opt/build_script.sh

# Setup entrypoint to configure permissions properly
COPY frontend_resources/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod u+x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Run build script on container start
CMD ["/bin/bash", "/opt/build_script.sh"]