version: '2'
services:
  labmanager:
    image: gigantum/labmanager-dev:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
     - "5000:5000"
     - "3000:3000"
    volumes:
    - /Users/dean/gigantum:/mnt/gigantum
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - LOCAL_USER_ID=501
     - HOST_WORK_DIR=/Users/dean/gigantum/
