version: '2'
services:
  labmanager:
    image: gigantum/labmanager-dev:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    command: /bin/bash
    ports:
     - "5000:5000"
     - "3000:3000"
    volumes:
    - {% WORKING_DIR %}:/mnt/gigantum:cached
    - /var/run/docker.sock:/var/run/docker.sock
    - {% GTM_DIR %}:/opt/project/:cached
    - labmanager_share_vol:/mnt/share
    environment:
     - WINDOWS_HOST=1
     - HOST_WORK_DIR={% WORKING_DIR %}
    network_mode: "bridge"

volumes:
  labmanager_share_vol:
    external: true
