# Set LabManger configuration file fields you wish to override from the default file stored in
# labmanager-common/lmcommon/configuration/config/labmanager.yaml.default
git:
  working_directory: "/mnt/gigantum"
  lfs_enabled: true
flask:
  DEBUG: false
  TESTING: false
container:
  cuda_version: null
environment:
  repo_url:
  - https://github.com/gigantum/environment-components.git@cuda